// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWADS83ihV5WTBayCmZSG3p6HsfujT8v0',
    appId: '1:757125260405:web:edd1f402703bb524e3043c',
    messagingSenderId: '757125260405',
    projectId: 'realtimedb-79cfd',
    authDomain: 'realtimedb-79cfd.firebaseapp.com',
    storageBucket: 'realtimedb-79cfd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxOn7LC2RGbe_IlbATIcerRye649IqKvk',
    appId: '1:757125260405:android:45566f9bfd09e532e3043c',
    messagingSenderId: '757125260405',
    projectId: 'realtimedb-79cfd',
    storageBucket: 'realtimedb-79cfd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBo5pqwuEo2vKeGWLMIspOMCsQ_bUXSTi8',
    appId: '1:757125260405:ios:4ca86c0643dc737ce3043c',
    messagingSenderId: '757125260405',
    projectId: 'realtimedb-79cfd',
    storageBucket: 'realtimedb-79cfd.appspot.com',
    iosBundleId: 'com.example.realtimeDb',
  );
}
